language: elixir
elixir:
  - 1.13.3
otp_release:
  - 24.0.2
services:
  - postgresql
env:
  - MIX_ENV=test
script: 
  - mix do setup, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - _build
  - deps
